language: android
sudo: false
android:
    components:
        - build-tools-23.0.0-preview
        - android-22
        - extra-android-m2repository
script:
    - cd opacclient
    - ./gradlew check lint
cache:
    directories:
        - $HOME/.gradle
